config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :toukous, only: [:new,:create,:index,:show,:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/toukou.rb
class Toukou < ApplicationRecord
  belongs_to :user
  attachment :location
  attachment :point
  attachment :result
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :toukous, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/toukous_controller.rb
class ToukousController < ApplicationController
  def new
    @toukou=Toukou.new
  end
  
  def create
    @toukou=Toukou.new(toukou_params)
    @toukou.user_id=current_user.id
    @toukou.save
    redirect_to toukou_path(@toukou.id)
  end
  
  def index
  end
  
  def show
    @toukou=Toukou.find(params[:id])
  end
  
  def destroy
  end
  
  private
  
  def toukou_params
    params.require(:toukou).permit(:map,:title,:location,:point,:result,:explain)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/toukous_helper.rb
module ToukousHelper
end

app/views/homes/top.html.erb
top

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Valotomo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li>
        <%= link_to '投稿フォーム', new_toukou_path %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/toukous/new.html.erb
<h1>投稿フォーム</h1>
<%= form_with model: @toukou,lacal:true do |f| %>
　<h4>マップ</h4>
　<%= f.select :map,[["アセント",1],["バインド",2],["ブリーズ",3],["フラクチャー",4],["ヘイブン",5],["アイスボックス",6],["ロータス",7],["パール",8],["スプリット",9]],include_blank: "マップを選択してください" %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>立ち位置</h4>
  <%= f.attachment_field :location %>
  <h4>目印</h4>
  <%= f.attachment_field :point %>
  <h4>結果</h4>
  <%= f.attachment_field :result %>
  <h4>説明</h4>
  <%= f.text_area :explain %>
  <%= f.submit "投稿" %>
<% end %>

app/views/toukous/show.html.erb
<div>
  <p>タイトル:<%= @toukou.title %></p>
  <P>立ち位置:<%= attachment_image_tag @toukou, :location %></P>
  <P>目印:<%= attachment_image_tag @toukou, :point %></P>
  <P>結果:<%= attachment_image_tag @toukou, :result %></P>
  <P>説明:<%= @toukou.explain %></P>
</div>